### ISSUE TITLE
Representere en eller flere roboter og vise denne frem på brettet

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodtorstige-robotet#3]

**Comment by kh498** [comment]
Daniel og jeg diskuterte dette i pm i slack. For dokumentasjons skyld kopierer jeg samtalen hit

![bilde](https://user-images.githubusercontent.com/1556738/51976067-177f1c00-2484-11e9-90d1-7aca6695fbfa.png)
![bilde](https://user-images.githubusercontent.com/1556738/51976108-2c5baf80-2484-11e9-996d-653e26afb400.png)

**Comment by kh498** [comment]
Litt sånn uformelt, men her en snippet hvor tiles despawner randomly (fra TiledMapHandler)

```java
private Random random = new Random();
    public void update(float delta) {
        if (Math.random() < 0.1) {
            TiledMapTileLayer layer = (TiledMapTileLayer) tiledMap.getLayers().get(0);
            layer.setCell(random.nextInt(mapWidth), random.nextInt(mapWidth), null);
        }
    } 
```

**Comment by DanielBerge** [comment]
Tuusen takk for den snippeten
